import {
    create,
    NTable,
    NButton,
    NCheckbox,
    NCheckboxGroup,
    NDataTable,
    NDatePicker,
    NForm,
    NFormItem,
    NFormItemGi,
    NGrid,
    NInput,
    NInputNumber,
    NLayout,
    NLayoutFooter,
    NLayoutHeader,
    NLayoutSider,
    NMenu,
    NRadio,
    NRadioButton,
    NRadioGroup,
    NResult,
    NSelect,
    NSlider,
    NSpace,
    NSwitch,
    NText,
    NTimePicker,
    NTransfer,
    NMessageProvider,
    NConfigProvider,
    NSpin,
    NLayoutContent,
    NAlert
} from 'naive-ui'

const NaiveUI = create({
    components: [
        NTable,
        NButton,
        NCheckbox,
        NCheckboxGroup,
        NDataTable,
        NDatePicker,
        NForm,
        NFormItem,
        NFormItemGi,
        NGrid,
        NInput,
        NInputNumber,
        NLayout,
        NLayoutFooter,
        NLayoutHeader,
        NLayoutSider,
        NMenu,
        NRadio,
        NRadioButton,
        NRadioGroup,
        NResult,
        NSelect,
        NSlider,
        NSpace,
        NSwitch,
        NText,
        NTimePicker,
        NTransfer,
        NMessageProvider,
        NConfigProvider,
        NSpin,
        NLayoutContent,
        NAlert
    ]
})

export default NaiveUI
